#define CRYPTO_SECRETKEYBYTES 32
#define CRYPTO_PUBLICKEYBYTES 64
#define CRYPTO_BYTES 64

#define SECRETKEY_BYTES CRYPTO_SECRETKEYBYTES
#define PUBLICKEY_BYTES CRYPTO_PUBLICKEYBYTES
#define SHAREDSECRET_BYTES CRYPTO_BYTES
