#define crypto_dh CRYPTO_NAMESPACETOP
#define crypto_dh_keypair CRYPTO_NAMESPACE(keypair)
#define crypto_dh_SECRETKEYBYTES crypto_dh_curve_2251_relic_amd64_clmul_SECRETKEYBYTES
#define crypto_dh_PUBLICKEYBYTES crypto_dh_curve_2251_relic_amd64_clmul_PUBLICKEYBYTES
#define crypto_dh_BYTES crypto_dh_curve_2251_relic_amd64_clmul_BYTES
