#define CRYPTO_KEYNIBBLES 32
#define CRYPTO_NPUBNIBBLES 0
#define CRYPTO_ANIBBLES 16

#define CRYPTO_KEYBYTES 16
#define CRYPTO_NSECBYTES 0
#define CRYPTO_NPUBBYTES 0
#define CRYPTO_ABYTES 8
#define CRYPTO_NOOVERLAP 1
