#include "crypto_sign.h"

#define SECRETKEY_BYTES crypto_sign_SECRETKEYBYTES
#define PUBLICKEY_BYTES crypto_sign_PUBLICKEYBYTES
#define PRIME_BYTES PUBLICKEY_BYTES
#define SHORTHASH_BYTES 64
#define SIGNATURE_BYTES 40
