*Build instructions

Platform: Linux  
Compiler: GCC

In order to build for Linux, change directory and run as follows:

cd McNie submission
cd Reference_Implementation
cd encrypt
cd 4Q_256_2
make
./4Q_256_2