#!/bin/sh

echo "=== `date` === hostname"
hostname || :

echo "=== `date` === uname -a"
uname -a || :
echo "=== `date` === uname -M"
uname -M || :
echo "=== `date` === uname -F"
uname -F || :

echo "=== `date` === /usr/sbin/lscfg | grep proc"
/usr/sbin/lscfg | grep proc || :
echo "=== `date` === /usr/sbin/lsattr -El proc0"
/usr/sbin/lsattr -El proc0 || :
echo "=== `date` === cat /proc/cpuinfo"
cat /proc/cpuinfo || :
echo "=== `date` === lscpu"
lscpu || :

echo "=== `date` === grep . /dev/null /sys/devices/system/cpu/cpu*/topology/physical_package_id"
grep . /dev/null /sys/devices/system/cpu/cpu*/topology/physical_package_id || :
echo "=== `date` === grep . /dev/null /sys/devices/system/cpu/cpu*/topology/core_id"
grep . /dev/null /sys/devices/system/cpu/cpu*/topology/core_id || :
echo "=== `date` === grep . /dev/null /sys/devices/system/cpu/cpu*/topology/thread_siblings_list"
grep . /dev/null /sys/devices/system/cpu/cpu*/topology/thread_siblings_list || :
echo "=== `date` === grep . /dev/null /sys/devices/system/cpu/cpu*/online"
grep . /dev/null /sys/devices/system/cpu/cpu*/online || :
echo "=== `date` === grep . /dev/null /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_min_freq"
grep . /dev/null /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_min_freq || :
echo "=== `date` === grep . /dev/null /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_max_freq"
grep . /dev/null /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_max_freq || :
echo "=== `date` === grep . /dev/null /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor"
grep . /dev/null /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor || :
echo "=== `date` === grep . /dev/null /sys/devices/system/cpu/cpu*/cpufreq/scaling_setspeed"
grep . /dev/null /sys/devices/system/cpu/cpu*/cpufreq/scaling_setspeed || :
echo "=== `date` === grep . /dev/null /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq"
grep . /dev/null /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq || :
echo "=== `date` === grep . /dev/null /sys/devices/system/cpu/cpu*/cpufreq/cpb"
grep . /dev/null /sys/devices/system/cpu/cpu*/cpufreq/cpb || :
echo "=== `date` === grep . /dev/null /sys/devices/system/cpu/intel_pstate/no_turbo"
grep . /dev/null /sys/devices/system/cpu/intel_pstate/no_turbo || :
echo "=== `date` === grep . /dev/null /sys/devices/intel_pt/max_nonturbo_ratio"
grep . /dev/null /sys/devices/intel_pt/max_nonturbo_ratio || :
echo "=== `date` === grep . /dev/null /sys/devices/system/cpu/cpu*/clock_tick"
grep . /dev/null /sys/devices/system/cpu/cpu*/clock_tick || :
echo "=== `date` === grep . /dev/null /sys/devices/system/cpu/cpu*/regs/identification/*"
grep . /dev/null /sys/devices/system/cpu/cpu*/regs/identification/* || :

echo "=== `date` === sysctl hw.model"
sysctl hw.model || :
echo "=== `date` === sysctl machdep.tsc_freq"
sysctl machdep.tsc_freq || :
echo "=== `date` === /usr/sbin/psrinfo -v"
/usr/sbin/psrinfo -v || :

echo "=== `date` === gcc --version"
gcc --version || :
echo "=== `date` === g++ --version"
g++ --version || :
echo "=== `date` === clang --version"
clang --version || :
echo "=== `date` === clang++ --version"
clang++ --version || :
echo "=== `date` === rustc --version"
rustc --version || :
echo "=== `date` === cargo --version"
cargo --version || :

# MacOS
echo "=== `date` === sw_vers"
sw_vers || :
echo "=== `date` === system_profiler -detailLevel mini"
system_profiler -detailLevel mini || :
echo "=== `date` === sysctl -n machdep.cpu.brand_string"
sysctl -n machdep.cpu.brand_string || :
