/**
 *  ff.c
 *  NTS-KEM
 *
 *  Parameter: NTS-KEM(13, 80)
 *  Platform: SSE2/SSE4.1
 *
 *  This file is part of the additional implemention of NTS-KEM
 *  submitted as part of NIST Post-Quantum Cryptography
 *  Standardization Process.
 **/

#include <stdlib.h>
#include <string.h>
#include "ff.h"

ff_unit ff_add_m(const FF2m* ff2m, ff_unit a, ff_unit b)
{
    return a ^ b;
}

ff_unit ff_reduce_13(uint32_t a)
{
    uint32_t u;
    
    /* GF(2^13), generated by f(x) = x^13 + x^4 + x^3 + x + 1 */
    u  = a & 0x1FF0000;
    a ^= (u >>  9);
    a ^= (u >> 10);
    a ^= (u >> 12);
    a ^= (u >> 13);
    
    u  = a & 0x000E000;
    a ^= (u >>  9);
    a ^= (u >> 10);
    a ^= (u >> 12);
    a ^= (u >> 13);
    
    return (ff_unit)(a & 0x1FFF);
}

ff_unit ff_mul_13(const FF2m* ff2m, ff_unit a, ff_unit b)
{
    uint32_t t;
    
    /* Perform shift-and-add multiplication */
    t  = a * (b & 1);
    t ^= (a * (b & 0x0002));
    t ^= (a * (b & 0x0004));
    t ^= (a * (b & 0x0008));
    t ^= (a * (b & 0x0010));
    t ^= (a * (b & 0x0020));
    t ^= (a * (b & 0x0040));
    t ^= (a * (b & 0x0080));
    t ^= (a * (b & 0x0100));
    t ^= (a * (b & 0x0200));
    t ^= (a * (b & 0x0400));
    t ^= (a * (b & 0x0800));
    t ^= (a * (b & 0x1000));
    
    /* Return the modulo reduction of t */
    return ff_reduce_13(t);
}

ff_unit ff_sqr_13(const FF2m* ff2m, ff_unit a)
{
    uint32_t b = a;
    
    b = (b | (b << 8)) & 0x00FF00FF;
    b = (b | (b << 4)) & 0x0F0F0F0F;
    b = (b | (b << 2)) & 0x33333333;
    b = (b | (b << 1)) & 0x55555555;
    
    return ff_reduce_13(b);
}

ff_unit ff_inv_13(const FF2m* ff2m, ff_unit a)
{
    ff_unit a3, a15, b;
    
    a3 = ff_sqr_13(ff2m, a);        /* a^2 */
    a3 = ff_mul_13(ff2m, a3, a);    /* a^3 */
    
    a15 = ff_sqr_13(ff2m, a3);      /* a^6 */
    a15 = ff_sqr_13(ff2m, a15);     /* a^12 */
    a15 = ff_mul_13(ff2m, a15, a3); /* a^15 */
    
    b = ff_sqr_13(ff2m, a15);       /* a^30 */
    b = ff_sqr_13(ff2m, b);         /* a^60 */
    b = ff_sqr_13(ff2m, b);         /* a^120 */
    b = ff_sqr_13(ff2m, b);         /* a^240 */
    b = ff_mul_13(ff2m, b, a15);    /* a^255 */
    
    b = ff_sqr_13(ff2m, b);         /* a^510 */
    b = ff_sqr_13(ff2m, b);         /* a^1020 */
    b = ff_mul_13(ff2m, b, a3);     /* a^1023 */
    
    b = ff_sqr_13(ff2m, b);         /* a^2046 */
    b = ff_sqr_13(ff2m, b);         /* a^4092 */
    b = ff_mul_13(ff2m, b, a3);     /* a^4095 */

    return ff_sqr_13(ff2m, b);      /* a^8190 */
}

void vector_ff_mul_13(const FF2m* ff2m, vector* c, const vector* a, const vector* b)
{
    vector t[13];
    
    /**
     * These sequences of & and ^ are obtained from here:
     * http://www.cs.yale.edu/homes/peralta/CircuitStuff/binary_pol_mult/B13size255depth8
     *
     * Circuit Minimization Work
     **/
    vector y1 = a[12] & b[0];
    vector y2 = a[12] & b[1];
    vector y3 = a[12] & b[2];
    vector y4 = a[12] & b[3];
    vector y5 = a[12] & b[4];
    vector y6 = a[12] & b[5];
    vector y7 = a[12] & b[6];
    vector y8 = a[12] & b[7];
    vector y9 = a[12] & b[8];
    vector y10 = a[12] & b[9];
    vector y11 = a[12] & b[10];
    vector y12 = a[12] & b[11];
    vector y13 = a[0] & b[12];
    vector y14 = a[1] & b[12];
    vector y15 = a[2] & b[12];
    vector y16 = a[3] & b[12];
    vector y17 = a[4] & b[12];
    vector y18 = a[5] & b[12];
    vector y19 = a[6] & b[12];
    vector y20 = a[7] & b[12];
    vector y21 = a[8] & b[12];
    vector y22 = a[9] & b[12];
    vector y23 = a[10] & b[12];
    vector y24 = a[11] & b[12];
    vector h23 = y12 ^ y24;
    vector y26 = a[11] & b[11];
    vector y27 = a[11] & b[9];
    vector y28 = a[11] & b[10];
    vector y29 = a[9] & b[11];
    vector y30 = a[10] & b[11];
    vector y31 = a[10] & b[10];
    vector y32 = a[10] & b[9];
    vector y33 = a[9] & b[10];
    vector y34 = a[9] & b[9];
    vector y35 = a[8] & b[8];
    vector y36 = a[8] & b[6];
    vector y37 = a[8] & b[7];
    vector y38 = a[6] & b[8];
    vector y39 = a[7] & b[8];
    vector y40 = a[7] & b[7];
    vector y41 = a[7] & b[6];
    vector y42 = a[6] & b[7];
    vector y43 = a[6] & b[6];
    vector y44 = a[5] & b[5];
    vector y45 = a[5] & b[3];
    vector y46 = a[5] & b[4];
    vector y47 = a[3] & b[5];
    vector y48 = a[4] & b[5];
    vector y49 = a[4] & b[4];
    vector y50 = a[4] & b[3];
    vector y51 = a[3] & b[4];
    vector y52 = a[3] & b[3];
    vector y53 = a[2] & b[2];
    vector y54 = a[2] & b[0];
    vector y55 = a[2] & b[1];
    vector y56 = a[0] & b[2];
    vector y57 = a[1] & b[2];
    vector y58 = a[1] & b[1];
    vector y59 = a[1] & b[0];
    vector y60 = a[0] & b[1];
    t[0] = a[0] & b[0];
    vector y62 = b[6] ^ b[9];
    vector y63 = b[7] ^ b[10];
    vector y64 = b[8] ^ b[11];
    vector y65 = a[6] ^ a[9];
    vector y66 = a[7] ^ a[10];
    vector y67 = a[8] ^ a[11];
    vector y68 = y67 & y64;
    vector y69 = y67 & y62;
    vector y70 = y67 & y63;
    vector y71 = y65 & y64;
    vector y72 = y66 & y64;
    vector y73 = y66 & y63;
    vector y74 = y66 & y62;
    vector y75 = y65 & y63;
    vector y76 = y65 & y62;
    vector y77 = b[0] ^ b[3];
    vector y78 = b[1] ^ b[4];
    vector y79 = b[2] ^ b[5];
    vector y80 = a[0] ^ a[3];
    vector y81 = a[1] ^ a[4];
    vector y82 = a[2] ^ a[5];
    vector y83 = y82 & y79;
    vector y84 = y82 & y77;
    vector y85 = y82 & y78;
    vector y86 = y80 & y79;
    vector y87 = y81 & y79;
    vector y88 = y81 & y78;
    vector y89 = y81 & y77;
    vector y90 = y80 & y78;
    vector y91 = y80 & y77;
    vector y92 = b[3] ^ b[9];
    vector y93 = b[4] ^ b[10];
    vector y94 = b[5] ^ b[11];
    vector y95 = b[0] ^ b[6];
    vector y96 = b[1] ^ b[7];
    vector y97 = b[2] ^ b[8];
    vector y98 = a[3] ^ a[9];
    vector y99 = a[4] ^ a[10];
    vector y100 = a[5] ^ a[11];
    vector y101 = a[0] ^ a[6];
    vector y102 = a[1] ^ a[7];
    vector y103 = a[2] ^ a[8];
    vector y104 = y103 & y97;
    vector y105 = y103 & y95;
    vector y106 = y103 & y96;
    vector y107 = y101 & y97;
    vector y108 = y102 & y97;
    vector y109 = y102 & y96;
    vector y110 = y102 & y95;
    vector y111 = y101 & y96;
    vector y112 = y101 & y95;
    vector y113 = y100 & y94;
    vector y114 = y100 & y92;
    vector y115 = y100 & y93;
    vector y116 = y98 & y94;
    vector y117 = y99 & y94;
    vector y118 = y99 & y93;
    vector y119 = y99 & y92;
    vector y120 = y98 & y93;
    vector y121 = y98 & y92;
    vector y122 = y95 ^ y92;
    vector y123 = y96 ^ y93;
    vector y124 = y97 ^ y94;
    vector y125 = y101 ^ y98;
    vector y126 = y102 ^ y99;
    vector y127 = y103 ^ y100;
    vector y128 = y127 & y124;
    vector y129 = y127 & y122;
    vector y130 = y127 & y123;
    vector y131 = y125 & y124;
    vector y132 = y126 & y124;
    vector y133 = y126 & y123;
    vector y134 = y126 & y122;
    vector y135 = y125 & y123;
    vector y136 = y125 & y122;
    vector y137 = y34 ^ y39;
    vector y138 = y52 ^ y57;
    vector y139 = y55 ^ y138;
    vector y140 = y43 ^ y46;
    vector y141 = y37 ^ y137;
    vector y142 = y28 ^ y30;
    vector y143 = y48 ^ y140;
    vector y144 = y141 ^ y142;
    vector y145 = y70 ^ y72;
    vector y146 = t[0] ^ y139;
    vector y147 = y115 ^ y117;
    vector y148 = y85 ^ y143;
    vector y149 = y76 ^ y143;
    vector y150 = y87 ^ y148;
    t[3] = y91 ^ y146;
    vector y152 = y106 ^ y121;
    vector y153 = y108 ^ y152;
    vector y154 = y144 ^ y147;
    vector y155 = y13 ^ y150;
    vector y156 = y139 ^ y155;
    vector y157 = y10 ^ y142;
    vector y158 = y149 ^ t[3];
    vector y159 = y112 ^ y150;
    vector y160 = y7 ^ y19;
    vector y161 = y1 ^ y132;
    vector y162 = y141 ^ y158;
    vector y163 = y4 ^ y154;
    vector y164 = y145 ^ y161;
    vector y165 = y149 ^ y163;
    vector y166 = y154 ^ y164;
    vector y167 = y136 ^ y153;
    vector h15 = y16 ^ y165;
    vector h21 = y22 ^ y157;
    vector y170 = y112 ^ y167;
    t[6] = y146 ^ y159;
    vector y172 = y130 ^ y153;
    vector y173 = y166 ^ y172;
    vector y174 = y144 ^ y160;
    vector h18 = y145 ^ y174;
    t[9] = y162 ^ y170;
    t[12] = y156 ^ y173;
    vector y178 = y42 ^ y44;
    vector y179 = y32 ^ y33;
    vector y180 = y35 ^ y179;
    vector y181 = y50 ^ y51;
    t[1] = y59 ^ y60;
    vector y183 = y41 ^ y178;
    vector y184 = y53 ^ y181;
    vector y185 = y26 ^ y180;
    vector y186 = t[1] ^ y184;
    vector y187 = y83 ^ y183;
    vector y188 = y119 ^ y120;
    vector y189 = y111 ^ y186;
    vector y190 = y110 ^ y189;
    vector y191 = y89 ^ y90;
    vector y192 = y104 ^ y188;
    vector y193 = y68 ^ y185;
    vector y194 = y74 ^ y183;
    vector y195 = y75 ^ y194;
    vector y196 = y134 ^ y195;
    vector y197 = y113 ^ y185;
    t[7] = y187 ^ y190;
    vector y199 = y135 ^ y191;
    vector y200 = y17 ^ y195;
    vector y201 = y113 ^ y193;
    vector y202 = y192 ^ y201;
    vector y203 = y2 ^ y128;
    vector y204 = y192 ^ y199;
    vector y205 = y5 ^ y200;
    vector h16 = y197 ^ y205;
    vector y207 = y180 ^ y196;
    vector y208 = y184 ^ y203;
    vector y209 = y187 ^ y208;
    vector y210 = y20 ^ y193;
    vector h19 = y8 ^ y210;
    t[4] = y186 ^ y191;
    vector y213 = y11 ^ y26;
    vector y214 = y190 ^ y204;
    t[10] = y207 ^ y214;
    vector y216 = y14 ^ y209;
    vector h22 = y23 ^ y213;
    vector h13 = y202 ^ y216;
    vector y219 = y27 ^ y31;
    vector y220 = y45 ^ y49;
    vector y221 = y47 ^ y220;
    vector y222 = y36 ^ y40;
    vector y223 = y54 ^ y56;
    vector y224 = y29 ^ y219;
    vector y225 = y38 ^ y222;
    t[2] = y58 ^ y223;
    vector y227 = y224 ^ y225;
    vector y228 = y221 ^ t[2];
    vector y229 = y69 ^ y71;
    vector y230 = y116 ^ y227;
    vector y231 = y84 ^ y88;
    vector y232 = y105 ^ y107;
    vector y233 = y86 ^ y228;
    vector y234 = y114 ^ y230;
    vector y235 = y118 ^ y234;
    vector y236 = y73 ^ y229;
    vector y237 = y109 ^ y232;
    t[5] = y231 ^ y233;
    vector y239 = y9 ^ y21;
    vector y240 = y225 ^ y237;
    vector h20 = y224 ^ y239;
    vector y242 = y236 ^ y237;
    vector y243 = y131 ^ y133;
    t[8] = y228 ^ y240;
    vector y245 = y15 ^ y221;
    vector y246 = y227 ^ y236;
    vector y247 = y18 ^ y246;
    vector y248 = y3 ^ y245;
    vector h17 = y6 ^ y247;
    vector h14 = y235 ^ y248;
    vector y251 = y129 ^ y243;
    vector y252 = y242 ^ y251;
    vector y253 = t[5] ^ y252;
    t[11] = y235 ^ y253;
    vector h24 = a[12] & b[12];
    
    /* Modulo reduction */
    h15   ^= h24; h14   ^= h24; t[12] ^= h24; t[11] ^= h24;
    h14   ^= h23; h13   ^= h23; t[11] ^= h23; t[10] ^= h23;
    h13   ^= h22; t[12] ^= h22; t[10] ^= h22; t[ 9] ^= h22;
    t[12] ^= h21; t[11] ^= h21; t[ 9] ^= h21; t[ 8] ^= h21;
    t[11] ^= h20; t[10] ^= h20; t[ 8] ^= h20; t[ 7] ^= h20;
    t[10] ^= h19; t[ 9] ^= h19; t[ 7] ^= h19; t[ 6] ^= h19;
    t[ 9] ^= h18; t[ 8] ^= h18; t[ 6] ^= h18; t[ 5] ^= h18;
    t[ 8] ^= h17; t[ 7] ^= h17; t[ 5] ^= h17; t[ 4] ^= h17;
    t[ 7] ^= h16; t[ 6] ^= h16; t[ 4] ^= h16; t[ 3] ^= h16;
    t[ 6] ^= h15; t[ 5] ^= h15; t[ 3] ^= h15; t[ 2] ^= h15;
    t[ 5] ^= h14; t[ 4] ^= h14; t[ 2] ^= h14; t[ 1] ^= h14;
    t[ 4] ^= h13; t[ 3] ^= h13; t[ 1] ^= h13; t[ 0] ^= h13;
    
    c[ 0] = t[ 0]; c[ 1] = t[ 1];
    c[ 2] = t[ 2]; c[ 3] = t[ 3];
    c[ 4] = t[ 4]; c[ 5] = t[ 5];
    c[ 6] = t[ 6]; c[ 7] = t[ 7];
    c[ 8] = t[ 8]; c[ 9] = t[ 9];
    c[10] = t[10]; c[11] = t[11];
    c[12] = t[12];
}

void vector_ff_sqr_13(const FF2m* ff2m, vector* b, const vector* a)
{
    b[12]  = a[11] ^ a[12];
    b[ 0]  = a[ 0] ^ a[11];
    b[ 1]  = b[12] ^ a[ 7];
    b[ 2]  = a[ 1] ^ a[ 7];
    b[ 3]  = b[12] ^ a[ 8];
    b[ 4]  = b[ 3] ^ a[ 2] ^ a[ 7];
    b[ 5]  = a[ 7] ^ a[ 9];
    b[ 6]  = a[ 3] ^ a[ 8] ^ a[ 9] ^ a[12];
    b[ 7]  = a[ 8] ^ a[10];
    b[ 8]  = a[ 4] ^ a[ 9] ^ a[10];
    b[ 9]  = a[ 9] ^ a[11];
    b[10]  = a[ 5] ^ a[10] ^ a[11];
    b[11]  = a[10] ^ a[12];
    b[12] ^= a[ 6];
}

void vector_ff_pow4_13(const FF2m* ff2m, vector* b, const vector* a)
{
    b[12]  = a[10] ^ a[11] ^ a[12];
    b[ 0]  = b[12] ^ a[ 0];
    b[ 1]  = a[ 6] ^ a[ 8] ^ a[11];
    b[ 2]  = b[12] ^ a[ 7] ^ a[ 8];
    b[ 3]  = a[ 4] ^ a[ 6] ^ a[ 9] ^ a[11];
    b[ 5]  = a[ 8] ^ a[ 9] ^ a[10] ^ a[11];
    b[ 4]  = b[ 5] ^ a[ 1] ^ a[ 4] ^ a[ 6] ^ a[ 7];
    b[ 6]  = a[ 4] ^ a[ 6] ^ a[ 8] ^ a[10] ^ a[11];
    b[ 7]  = a[ 4] ^ a[ 5] ^ a[ 9] ^ a[11];
    b[ 9]  = b[12] ^ a[ 9];
    b[10]  = b[ 9] ^ a[ 5] ^ a[ 7];
    b[ 8]  = b[10] ^ a[ 2] ^ a[ 8];
    b[10] ^= a[10];
    b[11]  = a[ 5] ^ a[ 6] ^ a[10] ^ a[12];
    b[12]  = b[ 9] ^ a[ 3] ^ a[ 6] ^ a[ 8];
}

void vector_ff_pow8_13(const FF2m* ff2m, vector* b, const vector* a)
{
    b[ 7]  = a[10] ^ a[12];
    b[ 0]  = a[ 0] ^ a[ 5] ^ a[ 6] ^ a[11];
    b[ 1]  = a[ 3] ^ a[ 4] ^ a[ 8];
    b[ 2]  = a[ 4] ^ a[ 5] ^ a[ 6] ^ a[ 8] ^ a[ 9];
    b[ 3]  = b[ 7] ^ a[ 2] ^ a[ 3] ^ a[ 7];
    b[ 4]  = b[ 1] ^ a[ 2] ^ a[ 5] ^ a[ 9];
    b[ 5]  = a[ 4] ^ a[ 5];
    b[ 6]  = b[ 3] ^ b[ 5];
    b[ 5] ^= b[ 7];
    b[ 7]  = a[ 2] ^ a[ 8] ^ a[10];
    b[ 8]  = b[ 2] ^ a[ 1] ^ a[11];
    b[ 9]  = a[ 5] ^ a[ 6] ^ a[ 9] ^ a[11];
    b[10]  = a[ 6] ^ a[ 7] ^ a[ 8];
    b[11]  = b[10] ^ a[ 3] ^ a[ 5] ^ a[10];
    b[12]  = b[ 9] ^ a[ 3] ^ a[ 4] ^ a[10] ^ a[11];
}

void vector_ff_pow16_13(const FF2m* ff2m, vector* b, const vector* a)
{
    b[10]  = a[ 3] ^ a[ 4];
    b[12]  = a[ 8] ^ a[ 9] ^ a[10];
    b[ 0]  = a[ 8] ^ a[10] ^ a[11];
    b[ 1]  = a[ 2] ^ a[ 4] ^ a[ 7] ^ a[ 9] ^ a[10];
    b[ 2]  = b[10] ^ a[ 2] ^ a[10];
    b[ 3]  = a[ 1] ^ a[ 5] ^ a[ 6] ^ a[ 7] ^ a[11];
    b[ 4]  = b[ 1] ^ a[ 1] ^ a[11];
    b[ 5]  = b[12] ^ a[ 2] ^ a[ 5] ^ a[ 6] ^ a[11];
    b[ 9]  = b[12] ^ a[ 3] ^ a[ 7] ^ a[11];
    b[11]  = b[10] ^ b[12] ^ a[ 5] ^ a[ 7];
    b[12] ^= (a[ 2] ^ a[ 5] ^ a[12]);
    b[ 6]  = b[12] ^ a[ 1] ^ a[ 6] ^ a[ 7] ^ a[10];
    b[12] ^= a[ 3];
    b[ 7]  = b[ 3] ^ a[ 6] ^ a[ 4] ^ a[ 9];
    b[ 8]  = b[ 2] ^ a[10] ^ a[ 7] ^ a[11];
    b[10] ^= a[12];
    b[ 0] ^= (a[ 0] ^ a[ 3] ^ a[ 7]);
}

void vector_ff_inv_13(const FF2m* ff2m, vector* b, const vector* a)
{
    vector a3[13], a15[13], t[13];
    
    vector_ff_sqr_13(ff2m, t, a);        /* a^2 */
    vector_ff_mul_13(ff2m, a3, t, a);    /* a^3 */
    
    vector_ff_pow4_13(ff2m, t, a3);      /* a^12 */
    vector_ff_mul_13(ff2m, a15, t, a3);  /* a^15 */
    
    vector_ff_pow16_13(ff2m, b, a15);    /* a^240 */
    vector_ff_mul_13(ff2m, t, b, a15);   /* a^255 */
    
    vector_ff_pow4_13(ff2m, b, t);       /* a^1020 */
    vector_ff_mul_13(ff2m, t, b, a3);    /* a^1023 */
    
    vector_ff_pow4_13(ff2m, b, t);       /* a^4092 */
    vector_ff_mul_13(ff2m, t, b, a3);    /* a^4095 */
    vector_ff_sqr_13(ff2m, b, t);        /* a^8190 */
}

void vector_ff_sqr_inv_13(const FF2m* ff2m, vector* b, const vector* a)
{
    vector a3[13], a15[13], t[13];
    
    vector_ff_sqr_13(ff2m, t, a);        /* a^2 */
    vector_ff_mul_13(ff2m, a3, t, a);    /* a^3 */
    
    vector_ff_pow4_13(ff2m, t, a3);      /* a^12 */
    vector_ff_mul_13(ff2m, a15, t, a3);  /* a^15 */
    
    vector_ff_pow16_13(ff2m, b, a15);    /* a^240 */
    vector_ff_mul_13(ff2m, t, b, a15);   /* a^255 */
    
    vector_ff_pow4_13(ff2m, b, t);       /* a^1020 */
    vector_ff_mul_13(ff2m, t, b, a3);    /* a^1023 */
    
    vector_ff_pow4_13(ff2m, b, t);       /* a^4092 */
    vector_ff_mul_13(ff2m, t, b, a3);    /* a^4095 */
    vector_ff_pow4_13(ff2m, b, t);       /* a^8189 */
}

ff_unit vector_ff_transpose_xor_13(const struct FF2m* ff2m,
                                   const vector* a)
{
    ff_unit s = 0;
    
    s  = (vector_popcount(a[ 0]) & 1);
    s |= (vector_popcount(a[ 1]) & 1) <<  1;
    s |= (vector_popcount(a[ 2]) & 1) <<  2;
    s |= (vector_popcount(a[ 3]) & 1) <<  3;
    s |= (vector_popcount(a[ 4]) & 1) <<  4;
    s |= (vector_popcount(a[ 5]) & 1) <<  5;
    s |= (vector_popcount(a[ 6]) & 1) <<  6;
    s |= (vector_popcount(a[ 7]) & 1) <<  7;
    s |= (vector_popcount(a[ 8]) & 1) <<  8;
    s |= (vector_popcount(a[ 9]) & 1) <<  9;
    s |= (vector_popcount(a[10]) & 1) << 10;
    s |= (vector_popcount(a[11]) & 1) << 11;
    s |= (vector_popcount(a[12]) & 1) << 12;
    
    return s;
}

FF2m* ff_create()
{
    int i;
    FF2m *ff2m = NULL;
    
    if (!(ff2m = (FF2m *)malloc(sizeof(FF2m))))
        return NULL;
    
    ff2m->m = 13;
    ff2m->ff_add = &ff_add_m;
    ff2m->ff_mul = &ff_mul_13;
    ff2m->ff_sqr = &ff_sqr_13;
    ff2m->ff_inv = &ff_inv_13;
    ff2m->vector_ff_mul = &vector_ff_mul_13;
    ff2m->vector_ff_sqr = &vector_ff_sqr_13;
    ff2m->vector_ff_inv = &vector_ff_inv_13;
    ff2m->vector_ff_sqr_inv = &vector_ff_sqr_inv_13;
    ff2m->vector_ff_transpose_xor = &vector_ff_transpose_xor_13;

    /**
     * Basis, B = <beta^{m-1},beta^{m-2},...,beta,1>
     **/
    if (!(ff2m->basis = (ff_unit *)calloc(ff2m->m, sizeof(ff_unit))))
        return NULL;
    for (i=0; i<ff2m->m; i++) {
        ff2m->basis[ff2m->m-i-1] = (1 << i);
    }
    
    return ff2m;
}

void ff_release(FF2m* ff2m)
{
    if (ff2m) {
        if (ff2m->basis) {
            memset(ff2m->basis, 0, ff2m->m*sizeof(ff_unit));
            free(ff2m->basis); ff2m->basis = NULL;
        }
        ff2m->m = 0;
        ff2m->ff_add = NULL;
        ff2m->ff_mul = NULL;
        ff2m->ff_sqr = NULL;
        ff2m->ff_inv = NULL;
        ff2m->vector_ff_mul = NULL;
        ff2m->vector_ff_sqr = NULL;
        ff2m->vector_ff_inv = NULL;
        ff2m->vector_ff_sqr_inv = NULL;
        ff2m->vector_ff_transpose_xor = NULL;
        free(ff2m);
    }
}

void bitslice_mul13_64(uint64_t* c, const uint64_t* a, const uint64_t* b)
{
    uint64_t t[13];
    
    /**
     * These sequences of & and ^ are obtained from here:
     * http://www.cs.yale.edu/homes/peralta/CircuitStuff/binary_pol_mult/B13size255depth8
     *
     * Circuit Minimization Work
     **/
    uint64_t y1 = a[12] & b[0];
    uint64_t y2 = a[12] & b[1];
    uint64_t y3 = a[12] & b[2];
    uint64_t y4 = a[12] & b[3];
    uint64_t y5 = a[12] & b[4];
    uint64_t y6 = a[12] & b[5];
    uint64_t y7 = a[12] & b[6];
    uint64_t y8 = a[12] & b[7];
    uint64_t y9 = a[12] & b[8];
    uint64_t y10 = a[12] & b[9];
    uint64_t y11 = a[12] & b[10];
    uint64_t y12 = a[12] & b[11];
    uint64_t y13 = a[0] & b[12];
    uint64_t y14 = a[1] & b[12];
    uint64_t y15 = a[2] & b[12];
    uint64_t y16 = a[3] & b[12];
    uint64_t y17 = a[4] & b[12];
    uint64_t y18 = a[5] & b[12];
    uint64_t y19 = a[6] & b[12];
    uint64_t y20 = a[7] & b[12];
    uint64_t y21 = a[8] & b[12];
    uint64_t y22 = a[9] & b[12];
    uint64_t y23 = a[10] & b[12];
    uint64_t y24 = a[11] & b[12];
    uint64_t h23 = y12 ^ y24;
    uint64_t y26 = a[11] & b[11];
    uint64_t y27 = a[11] & b[9];
    uint64_t y28 = a[11] & b[10];
    uint64_t y29 = a[9] & b[11];
    uint64_t y30 = a[10] & b[11];
    uint64_t y31 = a[10] & b[10];
    uint64_t y32 = a[10] & b[9];
    uint64_t y33 = a[9] & b[10];
    uint64_t y34 = a[9] & b[9];
    uint64_t y35 = a[8] & b[8];
    uint64_t y36 = a[8] & b[6];
    uint64_t y37 = a[8] & b[7];
    uint64_t y38 = a[6] & b[8];
    uint64_t y39 = a[7] & b[8];
    uint64_t y40 = a[7] & b[7];
    uint64_t y41 = a[7] & b[6];
    uint64_t y42 = a[6] & b[7];
    uint64_t y43 = a[6] & b[6];
    uint64_t y44 = a[5] & b[5];
    uint64_t y45 = a[5] & b[3];
    uint64_t y46 = a[5] & b[4];
    uint64_t y47 = a[3] & b[5];
    uint64_t y48 = a[4] & b[5];
    uint64_t y49 = a[4] & b[4];
    uint64_t y50 = a[4] & b[3];
    uint64_t y51 = a[3] & b[4];
    uint64_t y52 = a[3] & b[3];
    uint64_t y53 = a[2] & b[2];
    uint64_t y54 = a[2] & b[0];
    uint64_t y55 = a[2] & b[1];
    uint64_t y56 = a[0] & b[2];
    uint64_t y57 = a[1] & b[2];
    uint64_t y58 = a[1] & b[1];
    uint64_t y59 = a[1] & b[0];
    uint64_t y60 = a[0] & b[1];
    t[0] = a[0] & b[0];
    uint64_t y62 = b[6] ^ b[9];
    uint64_t y63 = b[7] ^ b[10];
    uint64_t y64 = b[8] ^ b[11];
    uint64_t y65 = a[6] ^ a[9];
    uint64_t y66 = a[7] ^ a[10];
    uint64_t y67 = a[8] ^ a[11];
    uint64_t y68 = y67 & y64;
    uint64_t y69 = y67 & y62;
    uint64_t y70 = y67 & y63;
    uint64_t y71 = y65 & y64;
    uint64_t y72 = y66 & y64;
    uint64_t y73 = y66 & y63;
    uint64_t y74 = y66 & y62;
    uint64_t y75 = y65 & y63;
    uint64_t y76 = y65 & y62;
    uint64_t y77 = b[0] ^ b[3];
    uint64_t y78 = b[1] ^ b[4];
    uint64_t y79 = b[2] ^ b[5];
    uint64_t y80 = a[0] ^ a[3];
    uint64_t y81 = a[1] ^ a[4];
    uint64_t y82 = a[2] ^ a[5];
    uint64_t y83 = y82 & y79;
    uint64_t y84 = y82 & y77;
    uint64_t y85 = y82 & y78;
    uint64_t y86 = y80 & y79;
    uint64_t y87 = y81 & y79;
    uint64_t y88 = y81 & y78;
    uint64_t y89 = y81 & y77;
    uint64_t y90 = y80 & y78;
    uint64_t y91 = y80 & y77;
    uint64_t y92 = b[3] ^ b[9];
    uint64_t y93 = b[4] ^ b[10];
    uint64_t y94 = b[5] ^ b[11];
    uint64_t y95 = b[0] ^ b[6];
    uint64_t y96 = b[1] ^ b[7];
    uint64_t y97 = b[2] ^ b[8];
    uint64_t y98 = a[3] ^ a[9];
    uint64_t y99 = a[4] ^ a[10];
    uint64_t y100 = a[5] ^ a[11];
    uint64_t y101 = a[0] ^ a[6];
    uint64_t y102 = a[1] ^ a[7];
    uint64_t y103 = a[2] ^ a[8];
    uint64_t y104 = y103 & y97;
    uint64_t y105 = y103 & y95;
    uint64_t y106 = y103 & y96;
    uint64_t y107 = y101 & y97;
    uint64_t y108 = y102 & y97;
    uint64_t y109 = y102 & y96;
    uint64_t y110 = y102 & y95;
    uint64_t y111 = y101 & y96;
    uint64_t y112 = y101 & y95;
    uint64_t y113 = y100 & y94;
    uint64_t y114 = y100 & y92;
    uint64_t y115 = y100 & y93;
    uint64_t y116 = y98 & y94;
    uint64_t y117 = y99 & y94;
    uint64_t y118 = y99 & y93;
    uint64_t y119 = y99 & y92;
    uint64_t y120 = y98 & y93;
    uint64_t y121 = y98 & y92;
    uint64_t y122 = y95 ^ y92;
    uint64_t y123 = y96 ^ y93;
    uint64_t y124 = y97 ^ y94;
    uint64_t y125 = y101 ^ y98;
    uint64_t y126 = y102 ^ y99;
    uint64_t y127 = y103 ^ y100;
    uint64_t y128 = y127 & y124;
    uint64_t y129 = y127 & y122;
    uint64_t y130 = y127 & y123;
    uint64_t y131 = y125 & y124;
    uint64_t y132 = y126 & y124;
    uint64_t y133 = y126 & y123;
    uint64_t y134 = y126 & y122;
    uint64_t y135 = y125 & y123;
    uint64_t y136 = y125 & y122;
    uint64_t y137 = y34 ^ y39;
    uint64_t y138 = y52 ^ y57;
    uint64_t y139 = y55 ^ y138;
    uint64_t y140 = y43 ^ y46;
    uint64_t y141 = y37 ^ y137;
    uint64_t y142 = y28 ^ y30;
    uint64_t y143 = y48 ^ y140;
    uint64_t y144 = y141 ^ y142;
    uint64_t y145 = y70 ^ y72;
    uint64_t y146 = t[0] ^ y139;
    uint64_t y147 = y115 ^ y117;
    uint64_t y148 = y85 ^ y143;
    uint64_t y149 = y76 ^ y143;
    uint64_t y150 = y87 ^ y148;
    t[3] = y91 ^ y146;
    uint64_t y152 = y106 ^ y121;
    uint64_t y153 = y108 ^ y152;
    uint64_t y154 = y144 ^ y147;
    uint64_t y155 = y13 ^ y150;
    uint64_t y156 = y139 ^ y155;
    uint64_t y157 = y10 ^ y142;
    uint64_t y158 = y149 ^ t[3];
    uint64_t y159 = y112 ^ y150;
    uint64_t y160 = y7 ^ y19;
    uint64_t y161 = y1 ^ y132;
    uint64_t y162 = y141 ^ y158;
    uint64_t y163 = y4 ^ y154;
    uint64_t y164 = y145 ^ y161;
    uint64_t y165 = y149 ^ y163;
    uint64_t y166 = y154 ^ y164;
    uint64_t y167 = y136 ^ y153;
    uint64_t h15 = y16 ^ y165;
    uint64_t h21 = y22 ^ y157;
    uint64_t y170 = y112 ^ y167;
    t[6] = y146 ^ y159;
    uint64_t y172 = y130 ^ y153;
    uint64_t y173 = y166 ^ y172;
    uint64_t y174 = y144 ^ y160;
    uint64_t h18 = y145 ^ y174;
    t[9] = y162 ^ y170;
    t[12] = y156 ^ y173;
    uint64_t y178 = y42 ^ y44;
    uint64_t y179 = y32 ^ y33;
    uint64_t y180 = y35 ^ y179;
    uint64_t y181 = y50 ^ y51;
    t[1] = y59 ^ y60;
    uint64_t y183 = y41 ^ y178;
    uint64_t y184 = y53 ^ y181;
    uint64_t y185 = y26 ^ y180;
    uint64_t y186 = t[1] ^ y184;
    uint64_t y187 = y83 ^ y183;
    uint64_t y188 = y119 ^ y120;
    uint64_t y189 = y111 ^ y186;
    uint64_t y190 = y110 ^ y189;
    uint64_t y191 = y89 ^ y90;
    uint64_t y192 = y104 ^ y188;
    uint64_t y193 = y68 ^ y185;
    uint64_t y194 = y74 ^ y183;
    uint64_t y195 = y75 ^ y194;
    uint64_t y196 = y134 ^ y195;
    uint64_t y197 = y113 ^ y185;
    t[7] = y187 ^ y190;
    uint64_t y199 = y135 ^ y191;
    uint64_t y200 = y17 ^ y195;
    uint64_t y201 = y113 ^ y193;
    uint64_t y202 = y192 ^ y201;
    uint64_t y203 = y2 ^ y128;
    uint64_t y204 = y192 ^ y199;
    uint64_t y205 = y5 ^ y200;
    uint64_t h16 = y197 ^ y205;
    uint64_t y207 = y180 ^ y196;
    uint64_t y208 = y184 ^ y203;
    uint64_t y209 = y187 ^ y208;
    uint64_t y210 = y20 ^ y193;
    uint64_t h19 = y8 ^ y210;
    t[4] = y186 ^ y191;
    uint64_t y213 = y11 ^ y26;
    uint64_t y214 = y190 ^ y204;
    t[10] = y207 ^ y214;
    uint64_t y216 = y14 ^ y209;
    uint64_t h22 = y23 ^ y213;
    uint64_t h13 = y202 ^ y216;
    uint64_t y219 = y27 ^ y31;
    uint64_t y220 = y45 ^ y49;
    uint64_t y221 = y47 ^ y220;
    uint64_t y222 = y36 ^ y40;
    uint64_t y223 = y54 ^ y56;
    uint64_t y224 = y29 ^ y219;
    uint64_t y225 = y38 ^ y222;
    t[2] = y58 ^ y223;
    uint64_t y227 = y224 ^ y225;
    uint64_t y228 = y221 ^ t[2];
    uint64_t y229 = y69 ^ y71;
    uint64_t y230 = y116 ^ y227;
    uint64_t y231 = y84 ^ y88;
    uint64_t y232 = y105 ^ y107;
    uint64_t y233 = y86 ^ y228;
    uint64_t y234 = y114 ^ y230;
    uint64_t y235 = y118 ^ y234;
    uint64_t y236 = y73 ^ y229;
    uint64_t y237 = y109 ^ y232;
    t[5] = y231 ^ y233;
    uint64_t y239 = y9 ^ y21;
    uint64_t y240 = y225 ^ y237;
    uint64_t h20 = y224 ^ y239;
    uint64_t y242 = y236 ^ y237;
    uint64_t y243 = y131 ^ y133;
    t[8] = y228 ^ y240;
    uint64_t y245 = y15 ^ y221;
    uint64_t y246 = y227 ^ y236;
    uint64_t y247 = y18 ^ y246;
    uint64_t y248 = y3 ^ y245;
    uint64_t h17 = y6 ^ y247;
    uint64_t h14 = y235 ^ y248;
    uint64_t y251 = y129 ^ y243;
    uint64_t y252 = y242 ^ y251;
    uint64_t y253 = t[5] ^ y252;
    t[11] = y235 ^ y253;
    uint64_t h24 = a[12] & b[12];
    
    /* Modulo reduction */
    h15   ^= h24; h14   ^= h24; t[12] ^= h24; t[11] ^= h24;
    h14   ^= h23; h13   ^= h23; t[11] ^= h23; t[10] ^= h23;
    h13   ^= h22; t[12] ^= h22; t[10] ^= h22; t[ 9] ^= h22;
    t[12] ^= h21; t[11] ^= h21; t[ 9] ^= h21; t[ 8] ^= h21;
    t[11] ^= h20; t[10] ^= h20; t[ 8] ^= h20; t[ 7] ^= h20;
    t[10] ^= h19; t[ 9] ^= h19; t[ 7] ^= h19; t[ 6] ^= h19;
    t[ 9] ^= h18; t[ 8] ^= h18; t[ 6] ^= h18; t[ 5] ^= h18;
    t[ 8] ^= h17; t[ 7] ^= h17; t[ 5] ^= h17; t[ 4] ^= h17;
    t[ 7] ^= h16; t[ 6] ^= h16; t[ 4] ^= h16; t[ 3] ^= h16;
    t[ 6] ^= h15; t[ 5] ^= h15; t[ 3] ^= h15; t[ 2] ^= h15;
    t[ 5] ^= h14; t[ 4] ^= h14; t[ 2] ^= h14; t[ 1] ^= h14;
    t[ 4] ^= h13; t[ 3] ^= h13; t[ 1] ^= h13; t[ 0] ^= h13;
    
    c[ 0] = t[ 0]; c[ 1] = t[ 1];
    c[ 2] = t[ 2]; c[ 3] = t[ 3];
    c[ 4] = t[ 4]; c[ 5] = t[ 5];
    c[ 6] = t[ 6]; c[ 7] = t[ 7];
    c[ 8] = t[ 8]; c[ 9] = t[ 9];
    c[10] = t[10]; c[11] = t[11];
    c[12] = t[12];
}

void bitslice_mul13_128(__m128i* c, const __m128i* a, const __m128i* b)
{
    __m128i t[13];
    
    /**
     * These sequences of & and ^ are obtained from here:
     * http://www.cs.yale.edu/homes/peralta/CircuitStuff/binary_pol_mult/B13size255depth8
     *
     * Circuit Minimization Work
     **/
    __m128i y1 = a[12] & b[0];
    __m128i y2 = a[12] & b[1];
    __m128i y3 = a[12] & b[2];
    __m128i y4 = a[12] & b[3];
    __m128i y5 = a[12] & b[4];
    __m128i y6 = a[12] & b[5];
    __m128i y7 = a[12] & b[6];
    __m128i y8 = a[12] & b[7];
    __m128i y9 = a[12] & b[8];
    __m128i y10 = a[12] & b[9];
    __m128i y11 = a[12] & b[10];
    __m128i y12 = a[12] & b[11];
    __m128i y13 = a[0] & b[12];
    __m128i y14 = a[1] & b[12];
    __m128i y15 = a[2] & b[12];
    __m128i y16 = a[3] & b[12];
    __m128i y17 = a[4] & b[12];
    __m128i y18 = a[5] & b[12];
    __m128i y19 = a[6] & b[12];
    __m128i y20 = a[7] & b[12];
    __m128i y21 = a[8] & b[12];
    __m128i y22 = a[9] & b[12];
    __m128i y23 = a[10] & b[12];
    __m128i y24 = a[11] & b[12];
    __m128i h23 = y12 ^ y24;
    __m128i y26 = a[11] & b[11];
    __m128i y27 = a[11] & b[9];
    __m128i y28 = a[11] & b[10];
    __m128i y29 = a[9] & b[11];
    __m128i y30 = a[10] & b[11];
    __m128i y31 = a[10] & b[10];
    __m128i y32 = a[10] & b[9];
    __m128i y33 = a[9] & b[10];
    __m128i y34 = a[9] & b[9];
    __m128i y35 = a[8] & b[8];
    __m128i y36 = a[8] & b[6];
    __m128i y37 = a[8] & b[7];
    __m128i y38 = a[6] & b[8];
    __m128i y39 = a[7] & b[8];
    __m128i y40 = a[7] & b[7];
    __m128i y41 = a[7] & b[6];
    __m128i y42 = a[6] & b[7];
    __m128i y43 = a[6] & b[6];
    __m128i y44 = a[5] & b[5];
    __m128i y45 = a[5] & b[3];
    __m128i y46 = a[5] & b[4];
    __m128i y47 = a[3] & b[5];
    __m128i y48 = a[4] & b[5];
    __m128i y49 = a[4] & b[4];
    __m128i y50 = a[4] & b[3];
    __m128i y51 = a[3] & b[4];
    __m128i y52 = a[3] & b[3];
    __m128i y53 = a[2] & b[2];
    __m128i y54 = a[2] & b[0];
    __m128i y55 = a[2] & b[1];
    __m128i y56 = a[0] & b[2];
    __m128i y57 = a[1] & b[2];
    __m128i y58 = a[1] & b[1];
    __m128i y59 = a[1] & b[0];
    __m128i y60 = a[0] & b[1];
    t[0] = a[0] & b[0];
    __m128i y62 = b[6] ^ b[9];
    __m128i y63 = b[7] ^ b[10];
    __m128i y64 = b[8] ^ b[11];
    __m128i y65 = a[6] ^ a[9];
    __m128i y66 = a[7] ^ a[10];
    __m128i y67 = a[8] ^ a[11];
    __m128i y68 = y67 & y64;
    __m128i y69 = y67 & y62;
    __m128i y70 = y67 & y63;
    __m128i y71 = y65 & y64;
    __m128i y72 = y66 & y64;
    __m128i y73 = y66 & y63;
    __m128i y74 = y66 & y62;
    __m128i y75 = y65 & y63;
    __m128i y76 = y65 & y62;
    __m128i y77 = b[0] ^ b[3];
    __m128i y78 = b[1] ^ b[4];
    __m128i y79 = b[2] ^ b[5];
    __m128i y80 = a[0] ^ a[3];
    __m128i y81 = a[1] ^ a[4];
    __m128i y82 = a[2] ^ a[5];
    __m128i y83 = y82 & y79;
    __m128i y84 = y82 & y77;
    __m128i y85 = y82 & y78;
    __m128i y86 = y80 & y79;
    __m128i y87 = y81 & y79;
    __m128i y88 = y81 & y78;
    __m128i y89 = y81 & y77;
    __m128i y90 = y80 & y78;
    __m128i y91 = y80 & y77;
    __m128i y92 = b[3] ^ b[9];
    __m128i y93 = b[4] ^ b[10];
    __m128i y94 = b[5] ^ b[11];
    __m128i y95 = b[0] ^ b[6];
    __m128i y96 = b[1] ^ b[7];
    __m128i y97 = b[2] ^ b[8];
    __m128i y98 = a[3] ^ a[9];
    __m128i y99 = a[4] ^ a[10];
    __m128i y100 = a[5] ^ a[11];
    __m128i y101 = a[0] ^ a[6];
    __m128i y102 = a[1] ^ a[7];
    __m128i y103 = a[2] ^ a[8];
    __m128i y104 = y103 & y97;
    __m128i y105 = y103 & y95;
    __m128i y106 = y103 & y96;
    __m128i y107 = y101 & y97;
    __m128i y108 = y102 & y97;
    __m128i y109 = y102 & y96;
    __m128i y110 = y102 & y95;
    __m128i y111 = y101 & y96;
    __m128i y112 = y101 & y95;
    __m128i y113 = y100 & y94;
    __m128i y114 = y100 & y92;
    __m128i y115 = y100 & y93;
    __m128i y116 = y98 & y94;
    __m128i y117 = y99 & y94;
    __m128i y118 = y99 & y93;
    __m128i y119 = y99 & y92;
    __m128i y120 = y98 & y93;
    __m128i y121 = y98 & y92;
    __m128i y122 = y95 ^ y92;
    __m128i y123 = y96 ^ y93;
    __m128i y124 = y97 ^ y94;
    __m128i y125 = y101 ^ y98;
    __m128i y126 = y102 ^ y99;
    __m128i y127 = y103 ^ y100;
    __m128i y128 = y127 & y124;
    __m128i y129 = y127 & y122;
    __m128i y130 = y127 & y123;
    __m128i y131 = y125 & y124;
    __m128i y132 = y126 & y124;
    __m128i y133 = y126 & y123;
    __m128i y134 = y126 & y122;
    __m128i y135 = y125 & y123;
    __m128i y136 = y125 & y122;
    __m128i y137 = y34 ^ y39;
    __m128i y138 = y52 ^ y57;
    __m128i y139 = y55 ^ y138;
    __m128i y140 = y43 ^ y46;
    __m128i y141 = y37 ^ y137;
    __m128i y142 = y28 ^ y30;
    __m128i y143 = y48 ^ y140;
    __m128i y144 = y141 ^ y142;
    __m128i y145 = y70 ^ y72;
    __m128i y146 = t[0] ^ y139;
    __m128i y147 = y115 ^ y117;
    __m128i y148 = y85 ^ y143;
    __m128i y149 = y76 ^ y143;
    __m128i y150 = y87 ^ y148;
    t[3] = y91 ^ y146;
    __m128i y152 = y106 ^ y121;
    __m128i y153 = y108 ^ y152;
    __m128i y154 = y144 ^ y147;
    __m128i y155 = y13 ^ y150;
    __m128i y156 = y139 ^ y155;
    __m128i y157 = y10 ^ y142;
    __m128i y158 = y149 ^ t[3];
    __m128i y159 = y112 ^ y150;
    __m128i y160 = y7 ^ y19;
    __m128i y161 = y1 ^ y132;
    __m128i y162 = y141 ^ y158;
    __m128i y163 = y4 ^ y154;
    __m128i y164 = y145 ^ y161;
    __m128i y165 = y149 ^ y163;
    __m128i y166 = y154 ^ y164;
    __m128i y167 = y136 ^ y153;
    __m128i h15 = y16 ^ y165;
    __m128i h21 = y22 ^ y157;
    __m128i y170 = y112 ^ y167;
    t[6] = y146 ^ y159;
    __m128i y172 = y130 ^ y153;
    __m128i y173 = y166 ^ y172;
    __m128i y174 = y144 ^ y160;
    __m128i h18 = y145 ^ y174;
    t[9] = y162 ^ y170;
    t[12] = y156 ^ y173;
    __m128i y178 = y42 ^ y44;
    __m128i y179 = y32 ^ y33;
    __m128i y180 = y35 ^ y179;
    __m128i y181 = y50 ^ y51;
    t[1] = y59 ^ y60;
    __m128i y183 = y41 ^ y178;
    __m128i y184 = y53 ^ y181;
    __m128i y185 = y26 ^ y180;
    __m128i y186 = t[1] ^ y184;
    __m128i y187 = y83 ^ y183;
    __m128i y188 = y119 ^ y120;
    __m128i y189 = y111 ^ y186;
    __m128i y190 = y110 ^ y189;
    __m128i y191 = y89 ^ y90;
    __m128i y192 = y104 ^ y188;
    __m128i y193 = y68 ^ y185;
    __m128i y194 = y74 ^ y183;
    __m128i y195 = y75 ^ y194;
    __m128i y196 = y134 ^ y195;
    __m128i y197 = y113 ^ y185;
    t[7] = y187 ^ y190;
    __m128i y199 = y135 ^ y191;
    __m128i y200 = y17 ^ y195;
    __m128i y201 = y113 ^ y193;
    __m128i y202 = y192 ^ y201;
    __m128i y203 = y2 ^ y128;
    __m128i y204 = y192 ^ y199;
    __m128i y205 = y5 ^ y200;
    __m128i h16 = y197 ^ y205;
    __m128i y207 = y180 ^ y196;
    __m128i y208 = y184 ^ y203;
    __m128i y209 = y187 ^ y208;
    __m128i y210 = y20 ^ y193;
    __m128i h19 = y8 ^ y210;
    t[4] = y186 ^ y191;
    __m128i y213 = y11 ^ y26;
    __m128i y214 = y190 ^ y204;
    t[10] = y207 ^ y214;
    __m128i y216 = y14 ^ y209;
    __m128i h22 = y23 ^ y213;
    __m128i h13 = y202 ^ y216;
    __m128i y219 = y27 ^ y31;
    __m128i y220 = y45 ^ y49;
    __m128i y221 = y47 ^ y220;
    __m128i y222 = y36 ^ y40;
    __m128i y223 = y54 ^ y56;
    __m128i y224 = y29 ^ y219;
    __m128i y225 = y38 ^ y222;
    t[2] = y58 ^ y223;
    __m128i y227 = y224 ^ y225;
    __m128i y228 = y221 ^ t[2];
    __m128i y229 = y69 ^ y71;
    __m128i y230 = y116 ^ y227;
    __m128i y231 = y84 ^ y88;
    __m128i y232 = y105 ^ y107;
    __m128i y233 = y86 ^ y228;
    __m128i y234 = y114 ^ y230;
    __m128i y235 = y118 ^ y234;
    __m128i y236 = y73 ^ y229;
    __m128i y237 = y109 ^ y232;
    t[5] = y231 ^ y233;
    __m128i y239 = y9 ^ y21;
    __m128i y240 = y225 ^ y237;
    __m128i h20 = y224 ^ y239;
    __m128i y242 = y236 ^ y237;
    __m128i y243 = y131 ^ y133;
    t[8] = y228 ^ y240;
    __m128i y245 = y15 ^ y221;
    __m128i y246 = y227 ^ y236;
    __m128i y247 = y18 ^ y246;
    __m128i y248 = y3 ^ y245;
    __m128i h17 = y6 ^ y247;
    __m128i h14 = y235 ^ y248;
    __m128i y251 = y129 ^ y243;
    __m128i y252 = y242 ^ y251;
    __m128i y253 = t[5] ^ y252;
    t[11] = y235 ^ y253;
    __m128i h24 = a[12] & b[12];
    
    /* Modulo reduction */
    h15   ^= h24; h14   ^= h24; t[12] ^= h24; t[11] ^= h24;
    h14   ^= h23; h13   ^= h23; t[11] ^= h23; t[10] ^= h23;
    h13   ^= h22; t[12] ^= h22; t[10] ^= h22; t[ 9] ^= h22;
    t[12] ^= h21; t[11] ^= h21; t[ 9] ^= h21; t[ 8] ^= h21;
    t[11] ^= h20; t[10] ^= h20; t[ 8] ^= h20; t[ 7] ^= h20;
    t[10] ^= h19; t[ 9] ^= h19; t[ 7] ^= h19; t[ 6] ^= h19;
    t[ 9] ^= h18; t[ 8] ^= h18; t[ 6] ^= h18; t[ 5] ^= h18;
    t[ 8] ^= h17; t[ 7] ^= h17; t[ 5] ^= h17; t[ 4] ^= h17;
    t[ 7] ^= h16; t[ 6] ^= h16; t[ 4] ^= h16; t[ 3] ^= h16;
    t[ 6] ^= h15; t[ 5] ^= h15; t[ 3] ^= h15; t[ 2] ^= h15;
    t[ 5] ^= h14; t[ 4] ^= h14; t[ 2] ^= h14; t[ 1] ^= h14;
    t[ 4] ^= h13; t[ 3] ^= h13; t[ 1] ^= h13; t[ 0] ^= h13;
    
    c[ 0] = t[ 0]; c[ 1] = t[ 1];
    c[ 2] = t[ 2]; c[ 3] = t[ 3];
    c[ 4] = t[ 4]; c[ 5] = t[ 5];
    c[ 6] = t[ 6]; c[ 7] = t[ 7];
    c[ 8] = t[ 8]; c[ 9] = t[ 9];
    c[10] = t[10]; c[11] = t[11];
    c[12] = t[12];
}
